// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8CFCRAIgkdkly9rB4hmqeHYIgtQIT5qg',
    appId: '1:1054104127433:web:bff6b39968fd708f81ca18',
    messagingSenderId: '1054104127433',
    projectId: 'snapspot-c9ace',
    authDomain: 'snapspot-c9ace.firebaseapp.com',
    storageBucket: 'snapspot-c9ace.firebasestorage.app',
    measurementId: 'G-M6H4M3Y8DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO5QZ0uVKGWeYHN71XyMbbRwzGxe2uRf0',
    appId: '1:1054104127433:android:5d8ec84e04b07a2981ca18',
    messagingSenderId: '1054104127433',
    projectId: 'snapspot-c9ace',
    storageBucket: 'snapspot-c9ace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOlg-66RhygJE52XfbmmpGdkkGu7ohrL0',
    appId: '1:1054104127433:ios:a3630f9d2a680fb881ca18',
    messagingSenderId: '1054104127433',
    projectId: 'snapspot-c9ace',
    storageBucket: 'snapspot-c9ace.firebasestorage.app',
    iosBundleId: 'com.example.appSnapspot',
  );
}
